controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_selecteur_restaurant:
  path: /Accueil
  controller: App\Controller\AccueilController::array
